# use feature_selector & auto-sklearn

In [ ]:
import pandas as pd
train_df = pd.read_csv("train.csv", encoding="utf-8")
train_df

In [ ]:
train_df["1暴露岩岸"] = train_df["1暴露岩岸"].fillna('0')
train_df["2暴露人造結構物"] = train_df["2暴露人造結構物"].fillna('0')
train_df["3暴露岩盤"] = train_df["3暴露岩盤"].fillna('0')
train_df["4沙灘"] = train_df["4沙灘"].fillna('0')
train_df["5砂礫混合灘"] = train_df["5砂礫混合灘"].fillna('0')
train_df["6礫石灘"] = train_df["6礫石灘"].fillna('0')
train_df["7開闊潮間帶"] = train_df["7開闊潮間帶"].fillna('0')
train_df["8遮蔽岩岸"] = train_df["8遮蔽岩岸"].fillna('0')
train_df["9遮蔽潮間帶"] = train_df["9遮蔽潮間帶"].fillna('0')
train_df["10遮蔽濕地"] = train_df["10遮蔽濕地"].fillna('0')

In [ ]:
dummy = pd.get_dummies(train_df["County"])
train_df = pd.concat([train_df, dummy], axis=1)
dummy = pd.get_dummies(train_df["Location"])
train_df = pd.concat([train_df, dummy], axis=1)
train_df

In [ ]:
from feature_selector import FeatureSelector
train_labels = train_df.LEVEL # 獲取all features 
train_features = train_df.drop(columns='LEVEL') # 創建 feature-selector 實例，並傳入features 和labels 
fs = FeatureSelector(data=train_features, labels=train_labels)
fs

In [ ]:
fs.identify_all(selection_params = {'missing_threshold': 0.6,    
                                    'correlation_threshold': 0.75, 
                                    'task': 'classification',    
                                    'eval_metric': 'auc', 
                                    'cumulative_importance': 0.8})

In [ ]:
train_removed_all = fs.remove(methods = 'all', keep_one_hot=True)

In [ ]:
train_removed_all

In [ ]:
train_removed_all = train_removed_all.drop(["Station", "Season", "County", "Location", "縣市"], axis=1)

In [ ]:
import autosklearn.classification
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics
x_train, x_vail, y_train, y_vail = sklearn.model_selection.train_test_split(train_removed_all, train_labels, random_state=1)
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(x_train, y_train)
y_hat = automl.predict(x_vail)
print("Accuracy score", sklearn.metrics.accuracy_score(y_vail, y_hat))

In [ ]:
automl.show_models()

In [ ]:
import sys
sys.exit()

# use auto-sklearn

In [1]:
import pandas as pd
train_df = pd.read_csv("train.csv", encoding="utf-8")
train_df

,Station,Season,County,Location,Lat,Lon,縣市,海岸段,Region,Seat,...,Foam material,Float,Fishing nets and ropes,Fishing equipment,Cigarette and lighter,Glass jar,Metal,Paper,Others,LEVEL
0,E02,1,宜蘭縣,大溪,24.92528,121.88569,16,5,1,4,...,0,0,0,1,0,0,0,0,0,2
1,E02,2,宜蘭縣,大溪,24.92528,121.88569,16,5,1,4,...,0,0,1,0,0,0,0,0,0,5
2,E02,3,宜蘭縣,大溪,24.92528,121.88569,16,5,1,4,...,0,0,0,0,0,1,0,0,0,2
3,E02,4,宜蘭縣,大溪,24.92528,121.88569,16,5,1,4,...,0,0,0,0,0,0,0,0,0,1
4,E03,1,宜蘭縣,頭城,24.85730,121.83342,16,5,1,4,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,TT02,4,台東縣長濱鄉中成,長光,23.32287,121.46538,14,5,4,3,...,0,1,0,0,0,0,0,0,0,2
315,TT03,1,台東縣長濱鄉,白桑安,23.24933,121.41867,14,5,4,4,...,0,0,0,0,0,0,0,0,0,3
316,TT03,2,台東縣長濱鄉,白桑安/長濱觀景平台,23.24933,121.41867,14,5,4,4,...,0,0,0,0,0,0,0,0,0,2
317,TT03,3,台東縣長濱鄉,白桑安/長濱觀景平台,23.24933,121.41867,14,5,4,4,...,0,0,1,0,0,0,0,0,0,3
318,TT03,4,台東縣長濱鄉,寜埔,23.24933,121.41867,14,5,4,4,...,0,0,0,0,0,0,0,0,0,1

In [2]:
print(train_df["1暴露岩岸"].value_counts().idxmax())
print(train_df["2暴露人造結構物"].value_counts().idxmax())
print(train_df["3暴露岩盤"].value_counts().idxmax())
print(train_df["4沙灘"].value_counts().idxmax())
print(train_df["5砂礫混合灘"].value_counts().idxmax())
print(train_df["6礫石灘"].value_counts().idxmax())
print(train_df["7開闊潮間帶"].value_counts().idxmax())
print(train_df["8遮蔽岩岸"].value_counts().idxmax())
print(train_df["9遮蔽潮間帶"].value_counts().idxmax())
print(train_df["10遮蔽濕地"].value_counts().idxmax())

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [3]:
train_df["1暴露岩岸"] = train_df["1暴露岩岸"].fillna('0')
train_df["2暴露人造結構物"] = train_df["2暴露人造結構物"].fillna('0')
train_df["3暴露岩盤"] = train_df["3暴露岩盤"].fillna('0')
train_df["4沙灘"] = train_df["4沙灘"].fillna('0')
train_df["5砂礫混合灘"] = train_df["5砂礫混合灘"].fillna('0')
train_df["6礫石灘"] = train_df["6礫石灘"].fillna('0')
train_df["7開闊潮間帶"] = train_df["7開闊潮間帶"].fillna('0')
train_df["8遮蔽岩岸"] = train_df["8遮蔽岩岸"].fillna('0')
train_df["9遮蔽潮間帶"] = train_df["9遮蔽潮間帶"].fillna('0')
train_df["10遮蔽濕地"] = train_df["10遮蔽濕地"].fillna('0')

In [4]:
train_df.isna().sum()

Station                               0
Season                                0
County                                0
Location                              0
Lat                                   0
Lon                                   0
縣市                                    0
海岸段                                   0
Region                                0
Seat                                  0
Shore shape                           0
Substrate type                        0
1暴露岩岸                                 0
2暴露人造結構物                              0
3暴露岩盤                                 0
4沙灘                                   0
5砂礫混合灘                                0
6礫石灘                                  0
7開闊潮間帶                                0
8遮蔽岩岸                                 0
9遮蔽潮間帶                                0
10遮蔽濕地                                0
Plastic bottle container              0
Disposable cup / straw / tableware    0
Plastic bag                           0
Foam material                         0
Float                                 0
Fishing nets and ropes                0
Fishing equipment                     0
Cigarette and lighter                 0
Glass jar                             0
Metal                                 0
Paper                                 0
Others                                0
LEVEL                                 0
dtype: int64

In [5]:
train_df['County'].value_counts()

宜蘭縣       24
新北        24
花蓮縣       15
屏東        12
屏東縣恆春鎮    10
          ..
台中市清水區     1
梓官區        1
彰化縣芳苑鄉     1
彰化縣芳苑      1
彰化鹿港       1
Name: County, Length: 63, dtype: int64

In [6]:
pd.set_option('max_columns', 50)
train_df

,Station,Season,County,Location,Lat,Lon,縣市,海岸段,Region,Seat,Shore shape,Substrate type,1暴露岩岸,2暴露人造結構物,3暴露岩盤,4沙灘,5砂礫混合灘,6礫石灘,7開闊潮間帶,8遮蔽岩岸,9遮蔽潮間帶,10遮蔽濕地,Plastic bottle container,Disposable cup / straw / tableware,Plastic bag,Foam material,Float,Fishing nets and ropes,Fishing equipment,Cigarette and lighter,Glass jar,Metal,Paper,Others,LEVEL
0,E02,1,宜蘭縣,大溪,24.92528,121.88569,16,5,1,4,2,3,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,2
1,E02,2,宜蘭縣,大溪,24.92528,121.88569,16,5,1,4,2,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,5
2,E02,3,宜蘭縣,大溪,24.92528,121.88569,16,5,1,4,2,3,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,2
3,E02,4,宜蘭縣,大溪,24.92528,121.88569,16,5,1,4,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,E03,1,宜蘭縣,頭城,24.85730,121.83342,16,5,1,4,1,4,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,TT02,4,台東縣長濱鄉中成,長光,23.32287,121.46538,14,5,4,3,2,5,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,2
315,TT03,1,台東縣長濱鄉,白桑安,23.24933,121.41867,14,5,4,4,2,4,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3
316,TT03,2,台東縣長濱鄉,白桑安/長濱觀景平台,23.24933,121.41867,14,5,4,4,2,4,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2
317,TT03,3,台東縣長濱鄉,白桑安/長濱觀景平台,23.24933,121.41867,14,5,4,4,2,4,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,3
318,TT03,4,台東縣長濱鄉,寜埔,23.24933,121.41867,14,5,4,4,2,4,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1

In [7]:
#one hot encoding
# dummy = pd.get_dummies(train_df["County"])
# train_df = pd.concat([train_df, dummy], axis=1)
# dummy = pd.get_dummies(train_df["Location"])
# train_df = pd.concat([train_df, dummy], axis=1)
# #dummy = pd.get_dummies(train_df["Station"])
# #train_df = pd.concat([train_df, dummy], axis=1)
# pd.set_option('max_columns', 1000)
# train_df

In [8]:
train_df = train_df.drop(["Location", "County", "Station"], axis=1)
train_df

,Season,Lat,Lon,縣市,海岸段,Region,Seat,Shore shape,Substrate type,1暴露岩岸,2暴露人造結構物,3暴露岩盤,4沙灘,5砂礫混合灘,6礫石灘,7開闊潮間帶,8遮蔽岩岸,9遮蔽潮間帶,10遮蔽濕地,Plastic bottle container,Disposable cup / straw / tableware,Plastic bag,Foam material,Float,Fishing nets and ropes,Fishing equipment,Cigarette and lighter,Glass jar,Metal,Paper,Others,LEVEL
0,1,24.92528,121.88569,16,5,1,4,2,3,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,2
1,2,24.92528,121.88569,16,5,1,4,2,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,5
2,3,24.92528,121.88569,16,5,1,4,2,3,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,2
3,4,24.92528,121.88569,16,5,1,4,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,1,24.85730,121.83342,16,5,1,4,1,4,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,4,23.32287,121.46538,14,5,4,3,2,5,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,2
315,1,23.24933,121.41867,14,5,4,4,2,4,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3
316,2,23.24933,121.41867,14,5,4,4,2,4,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2
317,3,23.24933,121.41867,14,5,4,4,2,4,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,3
318,4,23.24933,121.41867,14,5,4,4,2,4,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1

In [9]:
from sklearn.model_selection import train_test_split
y_train = train_df['LEVEL']
x_train = train_df.drop(['LEVEL'], axis=1)

x_train, x_valid, y_train, y_valid = train_test_split(x_train, y_train, test_size=0.3, random_state=1)

Auto_Sklearn

In [ ]:
import autosklearn.classification
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(x_train, y_train)
y_hat = automl.predict(x_valid)
print("Accuracy score", sklearn.metrics.accuracy_score(y_valid, y_hat))

In [ ]:
automl.show_models()

AdaBoostClassifier

In [10]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

/home/chengwei/miniconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [11]:
bdt = AdaBoostClassifier(DecisionTreeClassifier(max_depth=10, min_samples_split=20, min_samples_leaf=5), algorithm="SAMME",n_estimators=200, learning_rate=0.8)
bdt.fit(x_train, y_train)

AdaBoostClassifier(algorithm='SAMME',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=20,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=0.8, n_estimators=200, random_state=None)

In [12]:
bdt.feature_importances_

array([0.10025771, 0.12712469, 0.18086319, 0.0373323 , 0.01168515,
       0.02362756, 0.12341808, 0.02941485, 0.06134687, 0.00423189,
       0.01239086, 0.00267258, 0.0313713 , 0.02787892, 0.01225887,
       0.00526644, 0.00243388, 0.        , 0.        , 0.04023505,
       0.01626703, 0.0051228 , 0.046216  , 0.02007561, 0.05521922,
       0.        , 0.        , 0.01080815, 0.        , 0.        ,
       0.01248101])

In [13]:
bdt.predict(x_valid)

array([ 6,  6,  7,  5,  5,  5,  3,  6,  8,  3,  6,  3,  6,  3,  7,  7,  3,
        9,  5,  6,  8,  4,  5,  6,  6,  6,  7,  6,  6,  1,  5,  2,  4,  2,
        3,  3,  7,  2,  9,  2,  7,  8,  6,  2,  8,  8,  5, 10,  6,  3,  9,
        6,  7,  2,  8,  6,  8,  2,  8,  8,  2,  2,  6,  7,  6,  3,  2,  8,
        6,  6,  4,  8,  8,  6,  9,  4,  3,  2,  8,  8,  2,  9,  9,  8,  8,
        8,  7,  6,  6,  9,  7,  2,  6,  5,  5,  2])

In [14]:
bdt.score(x_valid,y_valid)

0.3125

Random Forest

In [ ]:
# 使用GridSearchCV套件計算最佳的參數，幾個弱分類器 + 深度
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
clf = RandomForestClassifier()
p = {
    "n_estimators":range(50, 80),
    "max_depth":range(10,20)
}
grid = GridSearchCV(clf, p, cv=10, n_jobs=4)
grid.fit(x_train, y_train)
grid.best_params_

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np
clf = RandomForestClassifier(n_estimators=50, max_depth=10)
s = cross_val_score(clf, x_train, y_train, cv=10) #交叉驗證
print("十次:", s)
print("平均:", np.average(s))

In [ ]:
import sklearn.metrics
clf = RandomForestClassifier(n_estimators=28, max_depth=11)
clf.fit(x_train, y_train)
y_hat = clf.predict(x_valid)
sklearn.metrics.accuracy_score(y_valid, y_hat, normalize=True, sample_weight=None)

# 載入測試集

In [70]:
test_df = pd.read_csv(r"test.csv", encoding="utf-8")
test_df

,Station,Season,County,Location,Lat,Lon,縣市,海岸段,Region,Seat,Shore shape,Substrate type,1暴露岩岸,2暴露人造結構物,3暴露岩盤,4沙灘,5砂礫混合灘,6礫石灘,7開闊潮間帶,8遮蔽岩岸,9遮蔽潮間帶,10遮蔽濕地,Plastic bottle container,Disposable cup / straw / tableware,Plastic bag,Foam material,Float,Fishing nets and ropes,Fishing equipment,Cigarette and lighter,Glass jar,Metal,Paper,Others
0,E01,1,宜蘭縣,石城,24.97876,121.94786,16,5,1,4,1,6,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,0,1,0,0,0,0,0,0,0,0,0
1,E01,2,宜蘭縣,石城,24.97876,121.94786,16,5,1,4,1,6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0,1,0,1,0,0,0,0,0,0
2,E01,3,宜蘭縣,石城,24.97876,121.94786,16,5,1,4,1,6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0,0,1,0,1,0,0,0,0,0,0
3,E01,4,宜蘭縣,石城,24.97876,121.94786,16,5,1,4,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,1,0,1,0,0,0,0,0,0
4,E04,1,宜蘭縣,永鎮,24.78206,121.81792,16,5,1,3,2,4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,TT01,4,台東縣長濱鄉樟原村,八仙北,23.40975,121.48345,14,5,4,3,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0
159,TT04,1,台東縣長濱鄉,石雨傘,23.17844,121.40177,14,5,4,2,1,4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,1,0,1,0,0,0,0,0,1
160,TT04,2,台東縣長濱鄉,石雨傘,23.17844,121.40177,14,5,4,2,1,4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,1
161,TT04,3,台東縣長濱鄉,石雨傘,23.17844,121.40177,14,5,4,2,1,4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,1,0,1,0,0,0,0,0,0
162,TT04,4,台東縣長濱鄉,石雨傘,23.17844,121.40177,14,5,4,2,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,1,0,1,0,0,0,0,0,1

In [71]:
print(test_df["1暴露岩岸"].value_counts().idxmax())
print(test_df["2暴露人造結構物"].value_counts().idxmax())
print(test_df["3暴露岩盤"].value_counts().idxmax())
print(test_df["4沙灘"].value_counts().idxmax())
print(test_df["5砂礫混合灘"].value_counts().idxmax())
print(test_df["6礫石灘"].value_counts().idxmax())
print(test_df["7開闊潮間帶"].value_counts().idxmax())
print(test_df["8遮蔽岩岸"].value_counts().idxmax())
print(test_df["9遮蔽潮間帶"].value_counts().idxmax())
print(test_df["10遮蔽濕地"].value_counts().idxmax())

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [72]:
test_df["1暴露岩岸"] = test_df["1暴露岩岸"].fillna('0')
test_df["2暴露人造結構物"] = test_df["2暴露人造結構物"].fillna('0')
test_df["3暴露岩盤"] = test_df["3暴露岩盤"].fillna('0')
test_df["4沙灘"] = test_df["4沙灘"].fillna('0')
test_df["5砂礫混合灘"] = test_df["5砂礫混合灘"].fillna('0')
test_df["6礫石灘"] = test_df["6礫石灘"].fillna('0')
test_df["7開闊潮間帶"] = test_df["7開闊潮間帶"].fillna('0')
test_df["8遮蔽岩岸"] = test_df["8遮蔽岩岸"].fillna('0')
test_df["9遮蔽潮間帶"] = test_df["9遮蔽潮間帶"].fillna('0')
test_df["10遮蔽濕地"] = test_df["10遮蔽濕地"].fillna('0')

In [73]:
# #one hot encoding
# dummy = pd.get_dummies(test_df["County"])
# test_df = pd.concat([test_df, dummy], axis=1)
# dummy = pd.get_dummies(test_df["Location"])
# test_df = pd.concat([test_df, dummy], axis=1)
# #dummy = pd.get_dummies(test_df["Station"])
# #test_df = pd.concat([test_df, dummy], axis=1)
# pd.set_option('max_columns', 1000)
# test_df

In [74]:
test_df = test_df.drop(["Location", "County", "Station"], axis=1)
test_df

,Season,Lat,Lon,縣市,海岸段,Region,Seat,Shore shape,Substrate type,1暴露岩岸,2暴露人造結構物,3暴露岩盤,4沙灘,5砂礫混合灘,6礫石灘,7開闊潮間帶,8遮蔽岩岸,9遮蔽潮間帶,10遮蔽濕地,Plastic bottle container,Disposable cup / straw / tableware,Plastic bag,Foam material,Float,Fishing nets and ropes,Fishing equipment,Cigarette and lighter,Glass jar,Metal,Paper,Others
0,1,24.97876,121.94786,16,5,1,4,1,6,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0
1,2,24.97876,121.94786,16,5,1,4,1,6,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0
2,3,24.97876,121.94786,16,5,1,4,1,6,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0
3,4,24.97876,121.94786,16,5,1,4,1,6,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0
4,1,24.78206,121.81792,16,5,1,3,2,4,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,4,23.40975,121.48345,14,5,4,3,2,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
159,1,23.17844,121.40177,14,5,4,2,1,4,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1
160,2,23.17844,121.40177,14,5,4,2,1,4,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
161,3,23.17844,121.40177,14,5,4,2,1,4,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0
162,4,23.17844,121.40177,14,5,4,2,1,4,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1

In [75]:
bdt.predict(test_df)

array([ 2,  7,  7,  6,  7,  7,  6,  6,  7,  1,  7,  2,  3,  1,  2,  2,  2,
        7,  2,  2,  4,  3,  2,  2,  5,  2,  2,  2,  7,  6,  2,  6,  8,  8,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  9,  7,  3,  6,  2,  6,  6,
        5,  5,  4,  7,  6,  6, 10,  6,  3,  5,  4,  6,  3,  2,  2,  2,  3,
        2,  2,  6,  9,  9,  9,  9,  6,  6,  2,  2,  9,  9,  9,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  7,  7,  8,  6,  5,  1,  5,  2,  5,  1,  2,
        2,  3,  1,  4,  2,  3,  1,  2,  2,  3,  8,  8,  8,  3,  3,  2,  3,
        5,  5,  5,  5,  3,  5,  7,  6,  6,  6,  6,  1,  7,  5,  5,  6,  5,
        4,  3,  3,  7,  2,  7,  2,  5,  2,  2,  6,  8,  8,  8,  6,  8,  8,
        8,  6,  3,  4,  5,  2,  9,  8,  8,  8])

In [76]:
#使用AdaBoost
ans = pd.read_csv(r"submission.csv", encoding="utf-8")
ans["LEVEL"] = bdt.predict(test_df).astype(int)
ans.to_csv("contest_adaboost.csv", encoding="utf-8", index=False)
ans

         ID  LEVEL
0     E01_1      2
1     E01_2      7
2     E01_3      7
3     E01_4      6
4     E04_1      7
..      ...    ...
158  TT01_4      2
159  TT04_1      9
160  TT04_2      8
161  TT04_3      8
162  TT04_4      8

[163 rows x 2 columns]